### ISSUE TITLE
Feature : Import/export in admin

### ISSUE THREAD

**Issue by gregpac** [linventifatelier/cartoterra#4]
Need an import button in admin views (for 'Buildings' first). Export of selected entries should also be possible as admin. First tests using django import export underway (http://django-import-export.readthedocs.org/en/latest/index.html)

**Comment by gregpac** [comment]
Import export successfully tested. pub_date automatically added as 'now' if pub_date field is left blank. 
Remains : 
• automatically add creator.id when creator field is left blank
• detect already existing coordinates, warning message, automatically suppress lines with already existing coordinates from imported table.

**Comment by legrostdg** [comment]
done  9bd717ede5e322fedc0c18b05296778b2c1f1a2c
